/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WesternToiletChinaRouteImport } from './routes/western-toilet-china'
import { Route as ToiletsInChinaRouteImport } from './routes/toilets-in-china'
import { Route as ToiletFinderChinaRouteImport } from './routes/toilet-finder-china'
import { Route as SquatToiletsChinaRouteImport } from './routes/squat-toilets-china'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ReportRouteImport } from './routes/report'
import { Route as PassRouteImport } from './routes/pass'
import { Route as ComplaintRouteImport } from './routes/complaint'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToiletIdRouteImport } from './routes/toilet.$id'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as CityPublicToiletsRouteImport } from './routes/$city.public-toilets'
import { Route as ApiStripeWebhookRouteImport } from './routes/api.stripe.webhook'

const WesternToiletChinaRoute = WesternToiletChinaRouteImport.update({
  id: '/western-toilet-china',
  path: '/western-toilet-china',
  getParentRoute: () => rootRouteImport,
} as any)
const ToiletsInChinaRoute = ToiletsInChinaRouteImport.update({
  id: '/toilets-in-china',
  path: '/toilets-in-china',
  getParentRoute: () => rootRouteImport,
} as any)
const ToiletFinderChinaRoute = ToiletFinderChinaRouteImport.update({
  id: '/toilet-finder-china',
  path: '/toilet-finder-china',
  getParentRoute: () => rootRouteImport,
} as any)
const SquatToiletsChinaRoute = SquatToiletsChinaRouteImport.update({
  id: '/squat-toilets-china',
  path: '/squat-toilets-china',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const PassRoute = PassRouteImport.update({
  id: '/pass',
  path: '/pass',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintRoute = ComplaintRouteImport.update({
  id: '/complaint',
  path: '/complaint',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToiletIdRoute = ToiletIdRouteImport.update({
  id: '/toilet/$id',
  path: '/toilet/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const CityPublicToiletsRoute = CityPublicToiletsRouteImport.update({
  id: '/$city/public-toilets',
  path: '/$city/public-toilets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/complaint': typeof ComplaintRoute
  '/pass': typeof PassRoute
  '/report': typeof ReportRoute
  '/saved': typeof SavedRoute
  '/squat-toilets-china': typeof SquatToiletsChinaRoute
  '/toilet-finder-china': typeof ToiletFinderChinaRoute
  '/toilets-in-china': typeof ToiletsInChinaRoute
  '/western-toilet-china': typeof WesternToiletChinaRoute
  '/$city/public-toilets': typeof CityPublicToiletsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/toilet/$id': typeof ToiletIdRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/complaint': typeof ComplaintRoute
  '/pass': typeof PassRoute
  '/report': typeof ReportRoute
  '/saved': typeof SavedRoute
  '/squat-toilets-china': typeof SquatToiletsChinaRoute
  '/toilet-finder-china': typeof ToiletFinderChinaRoute
  '/toilets-in-china': typeof ToiletsInChinaRoute
  '/western-toilet-china': typeof WesternToiletChinaRoute
  '/$city/public-toilets': typeof CityPublicToiletsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/toilet/$id': typeof ToiletIdRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/complaint': typeof ComplaintRoute
  '/pass': typeof PassRoute
  '/report': typeof ReportRoute
  '/saved': typeof SavedRoute
  '/squat-toilets-china': typeof SquatToiletsChinaRoute
  '/toilet-finder-china': typeof ToiletFinderChinaRoute
  '/toilets-in-china': typeof ToiletsInChinaRoute
  '/western-toilet-china': typeof WesternToiletChinaRoute
  '/$city/public-toilets': typeof CityPublicToiletsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/toilet/$id': typeof ToiletIdRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/complaint'
    | '/pass'
    | '/report'
    | '/saved'
    | '/squat-toilets-china'
    | '/toilet-finder-china'
    | '/toilets-in-china'
    | '/western-toilet-china'
    | '/$city/public-toilets'
    | '/admin/reports'
    | '/checkout/return'
    | '/toilet/$id'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/complaint'
    | '/pass'
    | '/report'
    | '/saved'
    | '/squat-toilets-china'
    | '/toilet-finder-china'
    | '/toilets-in-china'
    | '/western-toilet-china'
    | '/$city/public-toilets'
    | '/admin/reports'
    | '/checkout/return'
    | '/toilet/$id'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/complaint'
    | '/pass'
    | '/report'
    | '/saved'
    | '/squat-toilets-china'
    | '/toilet-finder-china'
    | '/toilets-in-china'
    | '/western-toilet-china'
    | '/$city/public-toilets'
    | '/admin/reports'
    | '/checkout/return'
    | '/toilet/$id'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComplaintRoute: typeof ComplaintRoute
  PassRoute: typeof PassRoute
  ReportRoute: typeof ReportRoute
  SavedRoute: typeof SavedRoute
  SquatToiletsChinaRoute: typeof SquatToiletsChinaRoute
  ToiletFinderChinaRoute: typeof ToiletFinderChinaRoute
  ToiletsInChinaRoute: typeof ToiletsInChinaRoute
  WesternToiletChinaRoute: typeof WesternToiletChinaRoute
  CityPublicToiletsRoute: typeof CityPublicToiletsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ToiletIdRoute: typeof ToiletIdRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/western-toilet-china': {
      id: '/western-toilet-china'
      path: '/western-toilet-china'
      fullPath: '/western-toilet-china'
      preLoaderRoute: typeof WesternToiletChinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toilets-in-china': {
      id: '/toilets-in-china'
      path: '/toilets-in-china'
      fullPath: '/toilets-in-china'
      preLoaderRoute: typeof ToiletsInChinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toilet-finder-china': {
      id: '/toilet-finder-china'
      path: '/toilet-finder-china'
      fullPath: '/toilet-finder-china'
      preLoaderRoute: typeof ToiletFinderChinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squat-toilets-china': {
      id: '/squat-toilets-china'
      path: '/squat-toilets-china'
      fullPath: '/squat-toilets-china'
      preLoaderRoute: typeof SquatToiletsChinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pass': {
      id: '/pass'
      path: '/pass'
      fullPath: '/pass'
      preLoaderRoute: typeof PassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaint': {
      id: '/complaint'
      path: '/complaint'
      fullPath: '/complaint'
      preLoaderRoute: typeof ComplaintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toilet/$id': {
      id: '/toilet/$id'
      path: '/toilet/$id'
      fullPath: '/toilet/$id'
      preLoaderRoute: typeof ToiletIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$city/public-toilets': {
      id: '/$city/public-toilets'
      path: '/$city/public-toilets'
      fullPath: '/$city/public-toilets'
      preLoaderRoute: typeof CityPublicToiletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComplaintRoute: ComplaintRoute,
  PassRoute: PassRoute,
  ReportRoute: ReportRoute,
  SavedRoute: SavedRoute,
  SquatToiletsChinaRoute: SquatToiletsChinaRoute,
  ToiletFinderChinaRoute: ToiletFinderChinaRoute,
  ToiletsInChinaRoute: ToiletsInChinaRoute,
  WesternToiletChinaRoute: WesternToiletChinaRoute,
  CityPublicToiletsRoute: CityPublicToiletsRoute,
  AdminReportsRoute: AdminReportsRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ToiletIdRoute: ToiletIdRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
